#!/bin/bash

if [ -z $GOPATH ]; then
    echo "FAIL: GOPATH environment variable is not set"
    exit 1
fi

if [ -n "$(go version | grep 'darwin/amd64')" ]; then
    GOOS="darwin_amd64"
elif [ -n "$(go version | grep 'linux/amd64')" ]; then
    GOOS="linux_amd64"
else
    echo "FAIL: only 64-bit Mac OS X and Linux operating systems are supported"
    exit 1
fi

go install github.com/cmu440-F15/paxosapp/gogrid
if [ $? -ne 0 ]; then
   echo "FAIL: code does not compile"
   exit $?
fi

$GOPATH/bin/gogrid -static $GOPATH/static -port 10086 -srvid 0
